config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get '/mango_kru/upload' => 'kru_members#upload_page', as: 'kru_member_upload'
  post '/mango_kru/upload' => 'kru_members#upload_action'
  resources :kru_members, path: 'mango_kru'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    p user
    user.roles.each do |role|
      puts role
      send(role)
    end
    guest unless user.roles.count
  end

  def guest
    can :read, :all
  end

  def admin
    guest
    can :access, :rails_admin # grant access to rails_admin
    can :dashboard
  end

  def kru_bulk_update
    can :import, KruMember
  end

  def kru_editor
    admin
    can :edit, KruMember
    can :new, KruMember
  end

  def kru_manager
    admin
    kru_editor
    kru_bulk_update
  end

  def superadmin
    admin
    kru_manager
    can :manage, :all
  end

end

app/models/kru_member.rb
# frozen_string_literal: true

class KruMember
  include Mongoid::Document
  include Mongoid::History::Trackable
  field :name, type: String
  field :image, type: String
  field :bio, type: String
  field :created_at, type: Time
  field :updated_at, type: Time

  track_history(
    track_create: false,
    track_destroy: true,
    track_update: true,
    modifier_field: :updater
  )

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Admin
  field :admin,              type: Boolean
  field :roles,              type: Array,   default: ['admin']

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def has_role?(role)
    roles.include? role
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :set_layout
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end
  # before_action :authenticate_user!


  private def set_layout
    @layout = 'default'
  end


end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  private def set_layout
    super
    @layout = 'frontpage'
  end
end

app/controllers/kru_members_controller.rb
# frozen_string_literal: true

class KruMembersController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit update destroy upload_page upload_action]
  before_action :set_kru_member, only: %i[show edit update destroy]

  # GET /kru_members
  # GET /kru_members.json
  def index
    @kru_members = KruMember.all
  end

  # GET /kru_members/1
  # GET /kru_members/1.json
  def show; end

  # GET /kru_members/new
  def new
    @kru_member = KruMember.new
  end

  # GET /kru_members/1/edit
  def edit; end

  # GET /kru_members/upload
  def upload_page
    authorize! :import, KruMember
    render :upload
  end

  # GET /kru_members/upload
  def upload_action
    kru_members = KruMembersHelper.load_upload_data upload_params[:data].read
    respond_to do |format|
      if KruMembersHelper.bulk_load kru_members, current_user
        format.html { redirect_to kru_members_url, notice: 'Kru members uploaded' }
      else
        format.html { redirect_to kru_member_upload_url, notice: 'Kru member upload failed' }
      end
    end
  end

  # POST /kru_members
  # POST /kru_members.json
  def create
    @kru_member = KruMember.new(kru_member_update_details(kru_member_params))
    respond_to do |format|
      if @kru_member.save
        format.html { redirect_to @kru_member, notice: 'Kru member was successfully created.' }
        format.json { render :show, status: :created, location: @kru_member }
      else
        format.html { render :new }
        format.json { render json: @kru_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kru_members/1
  # PATCH/PUT /kru_members/1.json
  def update
    respond_to do |format|
      if @kru_member.update(kru_member_update_details(kru_member_params))
        format.html { redirect_to @kru_member, notice: 'Kru member was successfully updated.' }
        format.json { render :show, status: :ok, location: @kru_member }
      else
        format.html { render :edit }
        format.json { render json: @kru_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kru_members/1
  # DELETE /kru_members/1.json
  def destroy
    @kru_member.destroy
    respond_to do |format|
      format.html { redirect_to kru_members_url, notice: 'Kru member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def kru_member_update_details(params)
    params[:updater]     = current_user
    params[:created_at] = Time.now
    params[:updated_at] = Time.now
    params
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_kru_member
    @kru_member = KruMember.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kru_member_params
    params.require(:kru_member).permit(:name, :image, :bio)
  end

  def upload_params
    params
  end

  private def set_layout
    super
    @layout = 'album'
  end
end

app/controllers/secure_controller.rb
# frozen_string_literal: true

class SecureController < ActionController::Base
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-error'
    when 'alert'
      'alert-block'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/kru_members_helper.rb
# frozen_string_literal: true

module KruMembersHelper
  def self.bulk_load(data, updater)
    data.each do |d|
      member = KruMember.where(name: d['name']).first
      if member
        member.update_attributes(d)
        member.updater = updater
        member.updated_at = Time.current
      else
        member = KruMember.new(d)
        member.updated_at = Time.current
        member.created_at = Time.current
        member.updater = updater
      end
      member.save
    end
  end

  def self.load_upload_data(data)
    YAML.load(data)
  end
end

app/views/home/index.html.haml
%div{align: 'center'}
  %h1 Da Oostin Boyeez

app/views/kru_members/_form.html.haml
= form_for @kru_member do |f|
  - if @kru_member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@kru_member.errors.count, "error")} prohibited this kru_member from being saved:"
      %ul
        - @kru_member.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :bio
    = f.text_field :bio
  .actions
    = f.submit 'Save'

app/views/kru_members/edit.html.haml
%h1 Editing kru_member

= render 'form'

= link_to 'Show', @kru_member
\|
= link_to 'Back', kru_members_path

app/views/kru_members/index.html.haml
%h1 Mango Kru
%p
%p
  .album.text-muted
    .container
      .row
        - @kru_members.each do |kru_member|
          .card{id: 'kruCard'}
            %div{align: 'center'}
              %img{alt: 'Card image cap', src: "/images/crew/#{kru_member.image}", class: 'kruImage'}

            %h5
              = link_to kru_member.name, kru_member
            %p.card-text
              = kru_member.bio

%br
- if can? :new, KruMember
  = link_to 'New Kru member', '/admin/kru_member/new'
- if can? :import, KruMember
  = link_to 'Import Kru members', kru_member_upload_path

app/views/kru_members/new.html.haml
%h1 New kru_member

= render 'form'

= link_to 'Back', kru_members_path

app/views/kru_members/show.html.haml
%p#notice= notice

%h1= @kru_member.name
.row
  %div{class: 'kruImageBlock col-sm-4'}
    %img{src: "/images/crew/#{@kru_member.image}", class: 'kruBioImage'}
  %div{class: 'col-sm-8'}
    = @kru_member.bio

= link_to 'Back', kru_members_path

app/views/kru_members/upload.html.haml
= form_tag({action: :upload_action}, multipart: true) do
  = file_field_tag 'data'
  = submit_tag

app/views/layouts/_album.html.haml
%div{class: 'container-fluid bgimg'}
  = yield

app/views/layouts/_default.html.haml
.container{class: 'bgimg'}
    = yield

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} ", :role => "alert"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/_footer.html.haml
%footer{class: 'footer'}
  %div{class: 'container-fluid'}
    LEEK

app/views/layouts/_frontpage.html.haml
%main
  = yield

app/views/layouts/_header.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  %a#brand.navbar-brand{:href => "#"} Da Oostin Boyeez
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item.active
        %a.nav-link{:href => '/'}
          Home
          %span.sr-only (current)
      %li.nav-item.active
        %a.nav-link{ :href => '/mango_kru' }
          Mango Kru
    %ul.nav.navbar-nav.navbar-toggler-right
      %li.nav-item.dropdown{:w => ''}
        %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"}
          Leek
        .dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}
          %a.dropdown-item{:href => rails_admin_path } Admin
          = link_to 'Logout', destroy_user_session_path, { class: 'dropdown-item', method: :delete }

app/views/layouts/_scripts.html.haml
%script{:crossorigin => "anonymous", :integrity => "sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n", :src => "https://code.jquery.com/jquery-3.1.1.slim.min.js"}
%script{:crossorigin => "anonymous", :integrity => "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb", :src => "https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Da Oostin Boyeez
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render partial:  'layouts/flash'
    %div{class: 'container'}
      = render "layouts/#{@layout}"
    = render 'layouts/footer'
    = render 'layouts/scripts'

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/